let problems = [
  {
    name: "Safe Clicking",
    description:
      "You're playing a game and a pop-up says 'Click here for free candy!' What should you do?",
    answer: "Close the pop-up and tell a grown-up",
    choices: [
      "Click on the pop-up",
      "Close the pop-up and tell a grown-up",
      "Ignore it",
      "Tell a friend",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Password Power",
    description: "Which of the following is a strong password?",
    answer: "Unicorn2023!",
    choices: ["password", "123456", "Unicorn2023!", "unicorn"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Phishing Fiasco",
    description:
      "Your friend sends you a message asking for your password. What should you do?",
    answer: "Never share your password, even with a friend",
    choices: [
      "Tell them the password",
      "Ignore the message",
      "Never share your password, even with a friend",
      "Tell them a fake password",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Internet Stranger Danger",
    description:
      "A stranger on the internet asks you for your real name. What should you do?",
    answer: "Don't tell them and let a grown-up know",
    choices: [
      "Tell them your name",
      "Ask them their name",
      "Don't tell them and let a grown-up know",
      "Tell them a fake name",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Download Dilemma",
    description:
      "You find a fun-looking game on a website you've never heard of. Should you download it?",
    answer: "No, only download games from trusted sources",
    choices: [
      "Yes, it looks fun",
      "No, only download games from trusted sources",
      "Download it and then delete it",
      "Ask a friend to download it",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Personal Info",
    description: "Is it okay to share your address online?",
    answer: "No, you should never share personal information online",
    choices: [
      "Yes, it's okay",
      "Only with friends",
      "No, you should never share personal information online",
      "Only if it's a trusted website",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Sharing Photos",
    description: "Should you share your photos with everyone online?",
    answer: "No, only share with people you and your parents know and trust",
    choices: [
      "Yes, it's fun to share",
      "No, only share with people you and your parents know and trust",
      "Only if the photos are funny",
      "Only with family",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Safe Websites",
    description: "How do you know if a website is safe?",
    answer: "Ask a grown-up for help",
    choices: [
      "If it has cool pictures",
      "If it lets you download games",
      "Ask a grown-up for help",
      "If it has no pop-ups",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Sharing Devices",
    description:
      "Should you let a friend use your device with your account logged in?",
    answer: "No, you should log out before letting a friend use your device",
    choices: [
      "Yes, sharing is caring",
      "No, you should log out before letting a friend use your device",
      "Only if they promise not to mess with anything",
      "Only if they are best friends",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Online Games",
    description:
      "You're playing an online game and someone you don't know asks to be your friend. What should you do?",
    answer: "Say no and tell a grown-up",
    choices: [
      "Say yes, more friends are good",
      "Say no and tell a grown-up",
      "Ask them for their real name",
      "Block them",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Update Time",
    description: "Your device asks you to install updates. What should you do?",
    answer: "Ask a grown-up for help",
    choices: [
      "Ignore the updates",
      "Ask a grown-up for help",
      "Install them right away",
      "Ask a friend",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Connected Devices",
    description: "Which of the following is a smart device?",
    answer: "A smartphone",
    choices: ["A toy car", "A pencil", "A smartphone", "A refrigerator"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Private Browsing",
    description: "Why might someone use private browsing?",
    answer: "To keep their browsing history private",
    choices: [
      "To play games",
      "To keep their browsing history private",
      "To watch funny videos",
      "To do homework",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Safe Search",
    description: "What does Safe Search do?",
    answer: "Helps block inappropriate content from search results",
    choices: [
      "Helps find the best games",
      "Helps block inappropriate content from search results",
      "Helps find funny videos",
      "Helps speed up searches",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Email Etiquette",
    description:
      "You receive an email from an unknown person. What should you do?",
    answer: "Ask a grown-up for help",
    choices: [
      "Open it and read it",
      "Reply to the email",
      "Ask a grown-up for help",
      "Delete the email",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Apps Permissions",
    description:
      "An app wants access to your camera and microphone, but it doesn't need them. What should you do?",
    answer: "Ask a grown-up for help",
    choices: [
      "Give the app permission",
      "Ignore the request",
      "Ask a grown-up for help",
      "Delete the app",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Social Media",
    description: "Is it okay for you to have your own social media account?",
    answer: "Ask a grown-up for help",
    choices: [
      "Yes, it's okay",
      "No, it's not okay",
      "Ask a grown-up for help",
      "Only if you're famous",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Location Sharing",
    description: "Should you share your location with everyone online?",
    answer: "No, you should never share your location with strangers",
    choices: [
      "Yes, it's okay",
      "No, you should never share your location with strangers",
      "Only with friends",
      "Only if you're lost",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Online Friends",
    description:
      "You met someone online who wants to meet you in person. What should you do?",
    answer: "Tell a grown-up immediately",
    choices: [
      "Yes, it sounds like fun",
      "No, you should never meet with strangers",
      "Tell a grown-up immediately",
      "Only if they bring snacks",
    ],
    selectedChoice: "",
    reward: 10,
  },
];

module.exports = problems;
