export let problemsArray = [
  {
    name: "passward",
    description: "どれが一番いいパスワード？",
    answer: "Maebashi2023City",
    choices: ["password", "cityMaebashi", "Tokyo2020"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "フィッシング🐟",
    description: "友達がスマホのパスワードを聞いてきた。どうする？",
    answer: "パスワードを教えない",
    choices: ["パスワードを教える", "無視する", "友達に嘘のパスワードを教える"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "ネットの知らない人とのやりとり",
    description: "ネットで知らない人から本名を聞かれた。どうする？",
    answer: "本名を教えない",
    choices: ["本名を教える", "相手の本名を聞く", "嘘の名前を教える"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "ダウンロード",
    description: "オンライン上で面白そうなブラウザゲームを発見した。どうする？",
    answer: "信頼できるサイトからしかダウンロードしない",
    choices: [
      "面白そうならダウンロードする",
      "ダウンロードしてから削除する",
      "友達にダウンロードしてもらう",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "個人情報",
    description: "SNSアプリで住所を友達に教えてもいい？",
    answer: "友達だけのチャットならOK",
    choices: ["OK", "友達だけに教える", "オンライン上では絶対に教えない"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "写真の共有",
    description: "オンライン上で写真をみんなと共有してもいい？",
    answer: "友達と家族だけにならOK",
    choices: ["OK", "写真が面白そうならOK", "個人情報がなければOK"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "安全なウェブサイト？",
    description: "どうやって安全なウェブサイトを見分ける？",
    answer: "URLを確認する",
    choices: [
      "画面がきれいか確認する",
      "試しにサイトにアクセスしてみる",
      "ポップアップが出てこなければ安全",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "アップデート",
    description: "スマホにアップデートの通知が。どうする？",
    answer: "時間があるときにアップデートする",
    choices: ["アップデートを無視する", "すぐにアップデートする", "友達に聞く"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "プライベートブラウジング",
    description: "プライベートブラウジングの目的は？",
    answer: "閲覧履歴を隠すため",
    choices: ["ゲームをするため", "面白い動画を見るため", "宿題をするため"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "セーフサーチ",
    description: "セーフサーチは何のため？",
    answer: "適切でない検索結果をブロックするため",
    choices: [
      "検索を快適に行うため",
      "検索結果を早く表示させるため",
      "個人情報を守るため",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "メール",
    description: "知らない人からメールが届いた。どうする？",
    answer: "送信元を確認する",
    choices: ["メールを開いて読む", "メールを消す", "返信する"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "アプリの許可",
    description: "アプリがカメラやマイクの使用を求めてきた。どうする？",
    answer: "アプリによって判断する",
    choices: ["許可する", "無視する", "アプリを消す"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "オンライン",
    description:
      "オンライン上で優しそうな青年と仲良くなった。どんな危険性がある？",
    answer: "実は怖いおじさんだった",
    choices: [
      "友達のお兄ちゃんだった",
      "両親のアカウントだった",
      "学校の先生だった",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "SNSの匿名性",
    description: "SNSで人に悪口を言われた。対処法として正しくないのは？",
    answer: "言い返す",
    choices: ["ブロックする", "無視する", "通報する"],
    selectedChoice: "",
    reward: 20,
  },
  {
    name: "パスワード",
    description: "パスワードの運用方法はどれがいい？",
    answer: "各サイトで違うパスワードを使う",
    choices: [
      "各サイトで同じパスワードを使う",
      "覚えやすいように生年月日を入れる",
      "名前と生年月日を入れる",
    ],
    selectedChoice: "",
    reward: 20,
  },
];
