export let problemsArray = [
  {
    name: "パスワード1",
    description: "どれが一番いいパスワード？",
    answer: "Maebashi1023City",
    choices: ["password", "cityMaebashi", "Tokyo2020"],
    selectedChoice: "",
    reward: 100,
  },
  {
    name: "パスワード2",
    description: "パスワードに関して、適切なのはどれ？",
    answer: "小文字と大文字のアルファベットと数字を使用する",
    choices: [
      "小文字と大文字のアルファベットを使用する",
      "名前と生年月日とペットの名前を組み合わせる",
      "パスワードは1つを使い回す",
    ],
    selectedChoice: "",
    reward: 200,
  },
  {
    name: "パスワード3",
    description: "適切なのはどれ？",
    answer: "パスワードは使い回さない",
    choices: [
      "パスワードは使い回す",
      "パスワードは友達に教えておく",
      "パスワードは覚えやすいものを使う",
    ],
    selectedChoice: "",
    reward: 300,
  },
  {
    name: "パスワード4",
    description: "どれが一番いいパスワード？",
    answer: "Maebashi1@23City",
    choices: ["Maebashi1023City", "City@Maebashi", "Tokyo2@2@"],
    selectedChoice: "",
    reward: 400,
  },
  {
    name: "友達とスマホ",
    description: "友達がスマホのパスワードを聞いてきた。どうする？",
    answer: "パスワードを教えない",
    choices: ["パスワードを教える", "無視する", "友達に嘘のパスワードを教える"],
    selectedChoice: "",
    reward: 100,
  },
  {
    name: "ネットの知らない人とのやりとり",
    description: "SNSで知らない人から本名を聞かれた。どうする？",
    answer: "本名を教えない",
    choices: ["本名を教える", "相手の本名を聞く", "嘘の名前を教える"],
    selectedChoice: "",
    reward: 100,
  },
  {
    name: "ダウンロード",
    description: "オンライン上で面白そうなブラウザゲームを発見した。どうする？",
    answer: "信頼できるサイトならダウンロードする",
    choices: [
      "面白そうならダウンロードする",
      "ダウンロードしてから削除する",
      "友達にダウンロードしてもらう",
    ],
    selectedChoice: "",
    reward: 100,
  },
  {
    name: "安全なウェブサイト？",
    description: "どうやって安全なウェブサイトを見分ける？",
    answer: "URLを確認する",
    choices: [
      "画面がきれいか確認する",
      "試しにサイトにアクセスしてみる",
      "ポップアップが出てこなければ安全",
    ],
    selectedChoice: "",
    reward: 100,
  },
  {
    name: "アップデート",
    description: "スマホにアップデートの通知が。どうする？",
    answer: "時間があるときにアップデートする",
    choices: ["アップデートを無視する", "すぐにアップデートする", "友達に聞く"],
    selectedChoice: "",
    reward: 100,
  },
  {
    name: "プライベートブラウジング",
    description: "プライベートブラウジングの目的は？",
    answer: "閲覧履歴を隠すため",
    choices: ["ゲームをするため", "面白い動画を見るため", "宿題をするため"],
    selectedChoice: "",
    reward: 100,
  },
  {
    name: "セーフサーチ",
    description: "セーフサーチは何のため？",
    answer: "適切でない検索結果をブロックするため",
    choices: [
      "検索を快適に行うため",
      "検索結果を早く表示させるため",
      "個人情報を守るため",
    ],
    selectedChoice: "",
    reward: 100,
  },
  {
    name: "メール",
    description: "知らない人からメールが届いた。どうする？",
    answer: "送信元を確認する",
    choices: ["メールを開いて読む", "メールを消す", "返信する"],
    selectedChoice: "",
    reward: 100,
  },
  {
    name: "アプリの許可",
    description: "アプリがカメラやマイクの使用を求めてきた。どうする？",
    answer: "アプリによって判断する",
    choices: ["許可する", "無視する", "アプリを消す"],
    selectedChoice: "",
    reward: 100,
  },
  {
    name: "オンライン",
    description:
      "オンライン上で優しそうな青年と仲良くなった。どんな危険性がある？",
    answer: "実は怖いおじさんだった",
    choices: [
      "友達のお兄ちゃんだった",
      "両親のアカウントだった",
      "学校の先生だった",
    ],
    selectedChoice: "",
    reward: 100,
  },
  {
    name: "SNSの匿名性",
    description: "SNSで人に悪口を言われた。対処法として正しくないのは？",
    answer: "言い返す",
    choices: ["ブロックする", "無視する", "通報する"],
    selectedChoice: "",
    reward: 200,
  },
  {
    name: "パスワード",
    description: "パスワードの運用方法はどれがいい？",
    answer: "各サイトで違うパスワードを使う",
    choices: [
      "各サイトで同じパスワードを使う",
      "覚えやすいように生年月日を入れる",
      "名前と生年月日を入れる",
    ],
    selectedChoice: "",
    reward: 200,
  },
  {
    name: "信頼できるサイト",
    description: "信頼できるサイトか見分けるにはどこを見る？",
    answer: "サイトのURL",
    choices: ["サイトのトップページ", "サイトのヘッダー", "サイトの名前"],
    selectedChoice: "",
    reward: 200,
  },
  {
    name: "危険なウェブサイト",
    description: "最も危険な可能性のあるウェブサイトはどれ？",
    answer: "http://から始まる",
    choices: ["https://から始まる", ".orgで終わる", ".jpで終わる"],
    selectedChoice: "",
    reward: 200,
  },
  {
    name: "フィッシング🐟",
    description:
      "知らない宛先からメールが届いた。メールにはURLが貼られている。どうする？",
    answer: "無視する",
    choices: [
      "URLをクリックしてサイトを確認する",
      "返信して送り主を確認する",
      "URLをコピーして友達に聞く",
    ],
    selectedChoice: "",
    reward: 200,
  },
];
