export let problemsArray_en = [
  {
    name: "Safe Clicking",
    description:
      "You're playing a game online and a pop-up says 'Click here for free candy!' What should you do?",
    answer: "Close the pop-up and tell a grown-up",
    choices: ["Click on the pop-up", "Ignore it", "Tell a friend"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Password Power",
    description: "Which of the following is a strong password?",
    answer: "Unicorn2023!",
    choices: ["password", "123456", "Unicorn2023!", "unicorn"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Phishing Fiasco",
    description:
      "Your friend sends you a message asking for your password. What should you do?",
    answer: "Never share your password, even with a friend",
    choices: [
      "Tell them the password",
      "Ignore the message",
      "Tell them a fake password",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Internet Stranger Danger",
    description:
      "A stranger on the internet asks you for your real name. What should you do?",
    answer: "Don't tell them",
    choices: [
      "Tell them your name",
      "Ask them their name",
      "Tell them a fake name",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Download Dilemma",
    description:
      "You find a fun-looking game on a website you've never heard of. Should you download it?",
    answer: "No, only download games from trusted sources",
    choices: [
      "Yes, it looks fun",
      "No, only download games from trusted sources",
      "Download it and then delete it",
      "Ask a friend to download it",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Personal Info",
    description: "Is it okay to share your address online?",
    answer: "No, you should never share personal information online",
    choices: [
      "Yes, it's okay",
      "Only with friends",
      "No, you should never share personal information online",
      "Only if it's a trusted website",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Sharing Photos",
    description: "Should you share your photos with everyone online?",
    answer: "No, only share with people you and your parents know and trust",
    choices: [
      "Yes, it's fun to share",
      "No, only share with people you and your parents know and trust",
      "Only if the photos are funny",
      "Only with family",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Safe Websites",
    description: "How do you know if a website is safe?",
    answer: "Ask a grown-up for help",
    choices: [
      "If it has cool pictures",
      "If it lets you download games",
      "Ask a grown-up for help",
      "If it has no pop-ups",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Sharing Devices",
    description:
      "Should you let a friend use your device with your account logged in?",
    answer: "No, you should log out before letting a friend use your device",
    choices: [
      "Yes, sharing is caring",
      "No, you should log out before letting a friend use your device",
      "Only if they promise not to mess with anything",
      "Only if they are best friends",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Online Games",
    description:
      "You're playing an online game and someone you don't know asks to be your friend. What should you do?",
    answer: "Say no and tell a grown-up",
    choices: [
      "Say yes, more friends are good",
      "Say no and tell a grown-up",
      "Ask them for their real name",
      "Block them",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Update Time",
    description: "Your device asks you to install updates. What should you do?",
    answer: "Ask a grown-up for help",
    choices: [
      "Ignore the updates",
      "Ask a grown-up for help",
      "Install them right away",
      "Ask a friend",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Connected Devices",
    description: "Which of the following is a smart device?",
    answer: "A smartphone",
    choices: ["A toy car", "A pencil", "A smartphone", "A refrigerator"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Private Browsing",
    description: "Why might someone use private browsing?",
    answer: "To keep their browsing history private",
    choices: [
      "To play games",
      "To keep their browsing history private",
      "To watch funny videos",
      "To do homework",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Safe Search",
    description: "What does Safe Search do?",
    answer: "Helps block inappropriate content from search results",
    choices: [
      "Helps find the best games",
      "Helps block inappropriate content from search results",
      "Helps find funny videos",
      "Helps speed up searches",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Email Etiquette",
    description:
      "You receive an email from an unknown person. What should you do?",
    answer: "Ask a grown-up for help",
    choices: [
      "Open it and read it",
      "Reply to the email",
      "Ask a grown-up for help",
      "Delete the email",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Apps Permissions",
    description:
      "An app wants access to your camera and microphone, but it doesn't need them. What should you do?",
    answer: "Ask a grown-up for help",
    choices: [
      "Give the app permission",
      "Ignore the request",
      "Ask a grown-up for help",
      "Delete the app",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Social Media",
    description: "Is it okay for you to have your own social media account?",
    answer: "Ask a grown-up for help",
    choices: [
      "Yes, it's okay",
      "No, it's not okay",
      "Ask a grown-up for help",
      "Only if you're famous",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Location Sharing",
    description: "Should you share your location with everyone online?",
    answer: "No, you should never share your location with strangers",
    choices: [
      "Yes, it's okay",
      "No, you should never share your location with strangers",
      "Only with friends",
      "Only if you're lost",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "Online Friends",
    description:
      "You met someone online who wants to meet you in person. What should you do?",
    answer: "Tell a grown-up immediately",
    choices: [
      "Yes, it sounds like fun",
      "No, you should never meet with strangers",
      "Tell a grown-up immediately",
      "Only if they bring snacks",
    ],
    selectedChoice: "",
    reward: 10,
  },
];

export let problemsArray = [
  {
    name: "passward",
    description: "どれが一番いいパスワード？",
    answer: "Maebashi2023City",
    choices: ["password", "cityMaebashi", "Tokyo2020"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "フィッシング🐟",
    description: "友達がスマホのパスワードを聞いてきた。どうする？",
    answer: "パスワードを教えない",
    choices: ["パスワードを教える", "無視する", "友達に嘘のパスワードを教える"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "ネットの知らない人とのやりとり",
    description: "ネットで知らない人から本名を聞かれた。どうする？",
    answer: "本名を教えない",
    choices: ["本名を教える", "相手の本名を聞く", "嘘の名前を教える"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "ダウンロード",
    description: "オンライン上で面白そうなブラウザゲームを発見した。どうする？",
    answer: "信頼できるサイトからしかダウンロードしない",
    choices: [
      "面白そうならダウンロードする",
      "ダウンロードしてから削除する",
      "友達にダウンロードしてもらう",
    ],
    selectedChoice: "",
    reward: 1,
  },
  {
    name: "個人情報",
    description: "SNSアプリで住所を友達に教えてもいい？",
    answer: "友達だけのチャットならOK",
    choices: ["OK", "友達だけに教える", "オンライン上では絶対に教えない"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "写真の共有",
    description: "オンライン上で写真をみんなと共有してもいい？",
    answer: "友達と家族だけにならOK",
    choices: ["OK", "写真が面白そうならOK", "個人情報がなければOK"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "安全なウェブサイト？",
    description: "どうやって安全なウェブサイトを見分ける？",
    answer: "URLを確認する",
    choices: [
      "画面がきれいか確認する",
      "試しにサイトにアクセスしてみる",
      "ポップアップが出てこなければ安全",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "アップデート",
    description: "スマホにアップデートの通知が。どうする？",
    answer: "時間があるときにアップデートする",
    choices: ["アップデートを無視する", "すぐにアップデートする", "友達に聞く"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "プライベートブラウジング",
    description: "プライベートブラウジングの目的は？",
    answer: "閲覧履歴を隠すため",
    choices: ["ゲームをするため", "面白い動画を見るため", "宿題をするため"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "セーフサーチ",
    description: "セーフサーチは何のため？",
    answer: "適切でない検索結果をブロックするため",
    choices: [
      "検索を快適に行うため",
      "検索結果を早く表示させるため",
      "個人情報を守るため",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "メール",
    description: "知らない人からメールが届いた。どうする？",
    answer: "送信元を確認する",
    choices: ["メールを開いて読む", "メールを消す", "返信する"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "アプリの許可",
    description: "アプリがカメラやマイクの使用を求めてきた。どうする？",
    answer: "アプリによって判断する",
    choices: ["許可する", "無視する", "アプリを消す"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "オンライン",
    description:
      "オンライン上で優しそうな青年と仲良くなった。どんな危険性がある？",
    answer: "実は怖いおじさんだった",
    choices: [
      "友達のお兄ちゃんだった",
      "両親のアカウントだった",
      "学校の先生だった",
    ],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "SNSの匿名性",
    description: "SNSで人に悪口を言われた。対処法として正しくないのは？",
    answer: "言い返す",
    choices: ["ブロックする", "無視する", "通報する"],
    selectedChoice: "",
    reward: 10,
  },
  {
    name: "パスワード",
    description: "パスワードの運用方法はどれがいい？",
    answer: "各サイトで違うパスワードを使う",
    choices: [
      "各サイトで同じパスワードを使う",
      "覚えやすいように生年月日を入れる",
      "名前と生年月日を入れる",
    ],
    selectedChoice: "",
    reward: 10,
  },
];
